#!/usr/bin/env bash
# Customising a 404 error page

#  Updating Packages before performing installations 
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World" | sudo tee /var/html/index.html

# Perfomring a "moved permanently redirection" (301)
new_string="server_name" _;\n\trewrite ^\/redirect_me https:\/\/github.com\/dellanox permanent ;"
sudo sed  -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom Error Page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
